services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception
    restart: unless-stopped

  nginx:
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/wordpress  # Volume partagé avec le service WordPress
    networks:
      - inception
    depends_on:
      - web-server
    build:
      context: requirements/nginx/  # Répertoire contenant le Dockerfile Nginx
      dockerfile: Dockerfile  # Assurez-vous que votre Dockerfile pour Nginx est dans ./nginx
    env_file:
      - .env
    ports:
      - "8080:80"  # Exposer le port 80 pour accéder à WordPress via Nginx
      - "443:443"
    restart: on-failure

  web-server:
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    expose:
      - 9000
    # ports:
    #   - "8080:80"
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:
    name: inception
    driver: bridge